# Generated by Django 2.0.1 on 2018-04-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_off', models.BooleanField(default=False)),
                ('energy_bal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('password', models.CharField(max_length=250)),
                ('Token', models.CharField(max_length=200)),
                ('meter_no', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='payment_main',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainserver.User_main'),
        ),
        migrations.AddField(
            model_name='meter_main',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainserver.User_main'),
        ),
    ]
