# Generated by Django 2.0.1 on 2018-04-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_main',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user_main',
            name='meter_no',
            field=models.IntegerField(blank=True),
        ),
    ]
