# Generated by Django 2.0.1 on 2018-05-01 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainserver', '0003_auto_20180419_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter_main',
            name='name',
        ),
        migrations.AddField(
            model_name='user_main',
            name='energy_bal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user_main',
            name='on_off',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Meter_main',
        ),
    ]
